### ISSUE TITLE
Job fails on final combine_gffs

### ISSUE THREAD

**Issue by selfjell** [sinanugur/MirMachine#9]
<img width="975" alt="Skjermbilde 2021-10-13 kl  12 28 18" src="https://user-images.githubusercontent.com/25090015/142419818-d967502a-473a-45bc-9c98-d78cbe258fe4.png">

**Comment by cement-head** [comment]
Did you find a solution?

**Comment by sinanugur** [comment]
Hi @cement-head ,

This is an old issue related to a dependency. You can use the latest version or our official Docker container.

Cheers,
@sinanugur
